publish:
  whoami: asf-blog
  type: blog

notifications:
  commits:      commits@hive.apache.org
  issues:       gitbox@hive.apache.org
  pullrequests: gitbox@hive.apache.org
  jira_options: link label worklog
